// AUTO-GENERATED by scripts/sync-edge-proof.mjs — do not edit.
// Source: lib/boardLayout.ts (SEC-16 colour assignment)
// Used to reject a color_corner that does not match the declared mode.

import type { ColorCorner, Corner } from './engine.ts';

/* eslint-disable @typescript-eslint/no-explicit-any -- lint burn-down quarantine 2026-09-23 */
import { PlayerColor, Corner, ColorCorner } from './types';
import { calculateLevel } from './progression';

export type Point = { r: number; c: number };

export type CellType = 'path' | 'home-lane' | 'home-base' | 'finish' | 'safe' | 'empty';

export interface PathCell {
    row: number;
    col: number;
    cls: string;
}

export type { Corner, ColorCorner };

// ─── Path Constants ──────────────────────────────────────────────────────────

/**
 * Programmatically generates the 52-cell shared perimeter path.
 * This starts from the standard 'Green' entry point (r: 6, c: 7) and follows
 * the clock-wise flow around the 15x15 grid.
 */
export const SHARED_PATH: Point[] = [
    // Top-Middle column 7 (bottom to top: r 6->1)
    { r: 6, c: 7 }, { r: 5, c: 7 }, { r: 4, c: 7 }, { r: 3, c: 7 }, { r: 2, c: 7 }, { r: 1, c: 7 },
    // Top crossover (r 1, c 8->9)
    { r: 1, c: 8 }, { r: 1, c: 9 },
    // Top-Middle column 9 (top to bottom: r 2->6)
    { r: 2, c: 9 }, { r: 3, c: 9 }, { r: 4, c: 9 }, { r: 5, c: 9 }, { r: 6, c: 9 },
    // Right-Middle row 7 (left to right: c 10->15)
    { r: 7, c: 10 }, { r: 7, c: 11 }, { r: 7, c: 12 }, { r: 7, c: 13 }, { r: 7, c: 14 }, { r: 7, c: 15 },
    // Right crossover (r 8->9, c 15)
    { r: 8, c: 15 }, { r: 9, c: 15 },
    // Right-Middle row 9 (right to left: c 14->10)
    { r: 9, c: 14 }, { r: 9, c: 13 }, { r: 9, c: 12 }, { r: 9, c: 11 }, { r: 9, c: 10 },
    // Bottom-Middle column 9 (top to bottom: r 10->15)
    { r: 10, c: 9 }, { r: 11, c: 9 }, { r: 12, c: 9 }, { r: 13, c: 9 }, { r: 14, c: 9 }, { r: 15, c: 9 },
    // Bottom crossover (r 15, c 8->7)
    { r: 15, c: 8 }, { r: 15, c: 7 },
    // Bottom-Middle column 7 (bottom to top: r 14->10)
    { r: 14, c: 7 }, { r: 13, c: 7 }, { r: 12, c: 7 }, { r: 11, c: 7 }, { r: 10, c: 7 },
    // Left-Middle row 9 (right to left: c 6->1)
    { r: 9, c: 6 }, { r: 9, c: 5 }, { r: 9, c: 4 }, { r: 9, c: 3 }, { r: 9, c: 2 }, { r: 9, c: 1 },
    // Left crossover (r 8->7, c 1)
    { r: 8, c: 1 }, { r: 7, c: 1 },
    // Left-Middle row 7 (left to right: c 2->6)
    { r: 7, c: 2 }, { r: 7, c: 3 }, { r: 7, c: 4 }, { r: 7, c: 5 }, { r: 7, c: 6 },
];

// Helper to shift the shared path for each player's start point
export const rotatePath = (points: Point[], startIndex: number): Point[] => {
    return [...points.slice(startIndex), ...points.slice(0, startIndex)];
};

// ─── Corner Slot Definitions (fixed by board geometry) ──────────────────────

export const CORNER_SLOTS: Record<Corner, {
    startIdx: number;
    homeCells: Point[];
    finishCell: Point;
    gridRow: string;
    gridCol: string;
    arrowDir: 'up' | 'down' | 'left' | 'right';
    arrowCell: Point;
    startCell: Point;
}> = {
    BL: {
        startIdx: 34,
        homeCells: [{ r: 14, c: 8 }, { r: 13, c: 8 }, { r: 12, c: 8 }, { r: 11, c: 8 }, { r: 10, c: 8 }],
        finishCell: { r: 9, c: 8 },
        gridRow: '10 / 16', gridCol: '1 / 7',
        arrowDir: 'up', arrowCell: { r: 14, c: 8 },
        startCell: { r: 14, c: 7 },
    },
    TR: {
        startIdx: 8,
        homeCells: [{ r: 2, c: 8 }, { r: 3, c: 8 }, { r: 4, c: 8 }, { r: 5, c: 8 }, { r: 6, c: 8 }],
        finishCell: { r: 7, c: 8 },
        gridRow: '1 / 7', gridCol: '10 / 16',
        arrowDir: 'down', arrowCell: { r: 2, c: 8 },
        startCell: { r: 2, c: 9 },
    },
    BR: {
        startIdx: 21,
        homeCells: [{ r: 8, c: 14 }, { r: 8, c: 13 }, { r: 8, c: 12 }, { r: 8, c: 11 }, { r: 8, c: 10 }],
        finishCell: { r: 8, c: 9 },
        gridRow: '10 / 16', gridCol: '10 / 16',
        arrowDir: 'left', arrowCell: { r: 8, c: 14 },
        startCell: { r: 9, c: 14 },
    },
    TL: {
        startIdx: 47,
        homeCells: [{ r: 8, c: 2 }, { r: 8, c: 3 }, { r: 8, c: 4 }, { r: 8, c: 5 }, { r: 8, c: 6 }],
        finishCell: { r: 8, c: 7 },
        gridRow: '1 / 7', gridCol: '1 / 7',
        arrowDir: 'right', arrowCell: { r: 8, c: 2 },
        startCell: { r: 7, c: 2 },
    },
};

/** Two valid diagonal axes for 2v2. Each entry = [axis corners for pair1, axis corners for pair2] */
const DIAGONAL_AXES: [readonly [Corner, Corner], readonly [Corner, Corner]][] = [
    [['BL', 'TR'], ['BR', 'TL']],  // Axis A
    [['BR', 'TL'], ['BL', 'TR']],  // Axis B (swapped)
];

/**
 * 2v2 mode: teammates are Green+Blue vs Red+Yellow (see TEAM_PAIRINGS).
 * Partners always land on diagonally opposite corners.
 * Which diagonal axis each team gets is randomized per match.
 */
export function assignCorners2v2(): ColorCorner {
    const teamGB: [PlayerColor, PlayerColor] = ['green', 'blue'];
    const teamRY: [PlayerColor, PlayerColor] = ['red', 'yellow'];

    // Pick a random diagonal axis
    const axis = DIAGONAL_AXES[Math.floor(Math.random() * 2)];
    // Randomly assign which team gets which diagonal axis
    const [axisGB, axisRY] = Math.random() < 0.5 ? [axis[0], axis[1]] : [axis[1], axis[0]];

    // Within each axis, randomly assign which teammate gets which corner
    const cc: Partial<ColorCorner> = {};
    const [gb0, gb1] = Math.random() < 0.5 ? axisGB : [axisGB[1], axisGB[0]];
    cc[teamGB[0]] = gb0;
    cc[teamGB[1]] = gb1;
    const [ry0, ry1] = Math.random() < 0.5 ? axisRY : [axisRY[1], axisRY[0]];
    cc[teamRY[0]] = ry0;
    cc[teamRY[1]] = ry1;

    return cc as ColorCorner;
}

/* eslint-disable @typescript-eslint/no-explicit-any -- lint burn-down quarantine 2026-09-23 */
import { PlayerColor, Corner, ColorCorner } from './types';
import { calculateLevel } from './progression';

export type Point = { r: number; c: number };

export type CellType = 'path' | 'home-lane' | 'home-base' | 'finish' | 'safe' | 'empty';

export interface PathCell {
    row: number;
    col: number;
    cls: string;
}

export type { Corner, ColorCorner };

// ─── Path Constants ──────────────────────────────────────────────────────────

/**
 * Programmatically generates the 52-cell shared perimeter path.
 * This starts from the standard 'Green' entry point (r: 6, c: 7) and follows
 * the clock-wise flow around the 15x15 grid.
 */
export const SHARED_PATH: Point[] = [
    // Top-Middle column 7 (bottom to top: r 6->1)
    { r: 6, c: 7 }, { r: 5, c: 7 }, { r: 4, c: 7 }, { r: 3, c: 7 }, { r: 2, c: 7 }, { r: 1, c: 7 },
    // Top crossover (r 1, c 8->9)
    { r: 1, c: 8 }, { r: 1, c: 9 },
    // Top-Middle column 9 (top to bottom: r 2->6)
    { r: 2, c: 9 }, { r: 3, c: 9 }, { r: 4, c: 9 }, { r: 5, c: 9 }, { r: 6, c: 9 },
    // Right-Middle row 7 (left to right: c 10->15)
    { r: 7, c: 10 }, { r: 7, c: 11 }, { r: 7, c: 12 }, { r: 7, c: 13 }, { r: 7, c: 14 }, { r: 7, c: 15 },
    // Right crossover (r 8->9, c 15)
    { r: 8, c: 15 }, { r: 9, c: 15 },
    // Right-Middle row 9 (right to left: c 14->10)
    { r: 9, c: 14 }, { r: 9, c: 13 }, { r: 9, c: 12 }, { r: 9, c: 11 }, { r: 9, c: 10 },
    // Bottom-Middle column 9 (top to bottom: r 10->15)
    { r: 10, c: 9 }, { r: 11, c: 9 }, { r: 12, c: 9 }, { r: 13, c: 9 }, { r: 14, c: 9 }, { r: 15, c: 9 },
    // Bottom crossover (r 15, c 8->7)
    { r: 15, c: 8 }, { r: 15, c: 7 },
    // Bottom-Middle column 7 (bottom to top: r 14->10)
    { r: 14, c: 7 }, { r: 13, c: 7 }, { r: 12, c: 7 }, { r: 11, c: 7 }, { r: 10, c: 7 },
    // Left-Middle row 9 (right to left: c 6->1)
    { r: 9, c: 6 }, { r: 9, c: 5 }, { r: 9, c: 4 }, { r: 9, c: 3 }, { r: 9, c: 2 }, { r: 9, c: 1 },
    // Left crossover (r 8->7, c 1)
    { r: 8, c: 1 }, { r: 7, c: 1 },
    // Left-Middle row 7 (left to right: c 2->6)
    { r: 7, c: 2 }, { r: 7, c: 3 }, { r: 7, c: 4 }, { r: 7, c: 5 }, { r: 7, c: 6 },
];

// Helper to shift the shared path for each player's start point
export const rotatePath = (points: Point[], startIndex: number): Point[] => {
    return [...points.slice(startIndex), ...points.slice(0, startIndex)];
};

// ─── Corner Slot Definitions (fixed by board geometry) ──────────────────────

export const CORNER_SLOTS: Record<Corner, {
    startIdx: number;
    homeCells: Point[];
    finishCell: Point;
    gridRow: string;
    gridCol: string;
    arrowDir: 'up' | 'down' | 'left' | 'right';
    arrowCell: Point;
    startCell: Point;
}> = {
    BL: {
        startIdx: 34,
        homeCells: [{ r: 14, c: 8 }, { r: 13, c: 8 }, { r: 12, c: 8 }, { r: 11, c: 8 }, { r: 10, c: 8 }],
        finishCell: { r: 9, c: 8 },
        gridRow: '10 / 16', gridCol: '1 / 7',
        arrowDir: 'up', arrowCell: { r: 14, c: 8 },
        startCell: { r: 14, c: 7 },
    },
    TR: {
        startIdx: 8,
        homeCells: [{ r: 2, c: 8 }, { r: 3, c: 8 }, { r: 4, c: 8 }, { r: 5, c: 8 }, { r: 6, c: 8 }],
        finishCell: { r: 7, c: 8 },
        gridRow: '1 / 7', gridCol: '10 / 16',
        arrowDir: 'down', arrowCell: { r: 2, c: 8 },
        startCell: { r: 2, c: 9 },
    },
    BR: {
        startIdx: 21,
        homeCells: [{ r: 8, c: 14 }, { r: 8, c: 13 }, { r: 8, c: 12 }, { r: 8, c: 11 }, { r: 8, c: 10 }],
        finishCell: { r: 8, c: 9 },
        gridRow: '10 / 16', gridCol: '10 / 16',
        arrowDir: 'left', arrowCell: { r: 8, c: 14 },
        startCell: { r: 9, c: 14 },
    },
    TL: {
        startIdx: 47,
        homeCells: [{ r: 8, c: 2 }, { r: 8, c: 3 }, { r: 8, c: 4 }, { r: 8, c: 5 }, { r: 8, c: 6 }],
        finishCell: { r: 8, c: 7 },
        gridRow: '1 / 7', gridCol: '1 / 7',
        arrowDir: 'right', arrowCell: { r: 8, c: 2 },
        startCell: { r: 7, c: 2 },
    },
};

/** Two valid diagonal axes for 2v2. Each entry = [axis corners for pair1, axis corners for pair2] */
const DIAGONAL_AXES: [readonly [Corner, Corner], readonly [Corner, Corner]][] = [
    [['BL', 'TR'], ['BR', 'TL']],  // Axis A
    [['BR', 'TL'], ['BL', 'TR']],  // Axis B (swapped)
];

/**
 * 2v2 mode: teammates are Green+Blue vs Red+Yellow (see TEAM_PAIRINGS).
 * Partners always land on diagonally opposite corners.
 * Which diagonal axis each team gets is randomized per match.
 */
export function assignCorners2v2(): ColorCorner {
    const teamGB: [PlayerColor, PlayerColor] = ['green', 'blue'];
    const teamRY: [PlayerColor, PlayerColor] = ['red', 'yellow'];

    // Pick a random diagonal axis
    const axis = DIAGONAL_AXES[Math.floor(Math.random() * 2)];
    // Randomly assign which team gets which diagonal axis
    const [axisGB, axisRY] = Math.random() < 0.5 ? [axis[0], axis[1]] : [axis[1], axis[0]];

    // Within each axis, randomly assign which teammate gets which corner
    const cc: Partial<ColorCorner> = {};
    const [gb0, gb1] = Math.random() < 0.5 ? axisGB : [axisGB[1], axisGB[0]];
    cc[teamGB[0]] = gb0;
    cc[teamGB[1]] = gb1;
    const [ry0, ry1] = Math.random() < 0.5 ? axisRY : [axisRY[1], axisRY[0]];
    cc[teamRY[0]] = ry0;
    cc[teamRY[1]] = ry1;

    return cc as ColorCorner;
}

/**
 * 1v1 / 4P free-for-all: Full Fisher-Yates shuffle of corners — no pairing constraints.
 */
export function assignCornersFFA(playerCount: '1v1' | '4P' = '4P'): ColorCorner {
    const cc: Partial<ColorCorner> = {};
    const allColors: PlayerColor[] = ['green', 'red', 'yellow', 'blue'];
    const corners: Corner[] = ['BL', 'BR', 'TR', 'TL'];

    if (playerCount === '1v1') {
        // For 1v1, we MUST ensure the two active players (first two in LOBBY_COLORS)
        // are diagonally opposite. We'll pick one axis randomly.
        // The remaining colors still receive the unused diagonal so coordinate
        // lookups remain total even though they are not seated in this match.
        const axis = Math.random() < 0.5 ? ['BL', 'TR'] : ['BR', 'TL'];
        const otherAxis = axis[0] === 'BL' ? ['BR', 'TL'] : ['BL', 'TR'];
        
        // Randomly assign the first two colors to the chosen axis
        const [c0, c1] = Math.random() < 0.5 ? axis : [axis[1], axis[0]];
        cc[allColors[0]] = c0 as Corner; // Host (Green)
        cc[allColors[2]] = c1 as Corner; // Guest (Yellow)
        
        // Assign remaining colors to the other axis
        const [c2, c3] = Math.random() < 0.5 ? otherAxis : [otherAxis[1], otherAxis[0]];
        cc[allColors[1]] = c2 as Corner; // Red
        cc[allColors[3]] = c3 as Corner; // Blue
    } else {
        // Fisher-Yates shuffle corners for 4P
        for (let i = corners.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [corners[i], corners[j]] = [corners[j], corners[i]];
        }
        // Assign all 4 colors to corners
        allColors.forEach((color, i) => { cc[color] = corners[i]; });
    }

    return cc as ColorCorner;
}
