// AUTO-GENERATED by scripts/sync-edge-proof.mjs — do not edit.
// Source: lib/boardLayout.ts (SEC-16 colour assignment)
// Used to reject a color_corner that does not match the declared mode.

import type { ColorCorner, Corner, PlayerColor } from './engine.ts';

export function assignCorners2v2(): ColorCorner {
    const teamGB: [PlayerColor, PlayerColor] = ['green', 'blue'];
    const teamRY: [PlayerColor, PlayerColor] = ['red', 'yellow'];

    // Pick a random diagonal axis
    const axis = DIAGONAL_AXES[Math.floor(Math.random() * 2)];
    // Randomly assign which team gets which diagonal axis
    const [axisGB, axisRY] = Math.random() < 0.5 ? [axis[0], axis[1]] : [axis[1], axis[0]];

    // Within each axis, randomly assign which teammate gets which corner
    const cc: Partial<ColorCorner> = {};
    const [gb0, gb1] = Math.random() < 0.5 ? axisGB : [axisGB[1], axisGB[0]];
    cc[teamGB[0]] = gb0;
    cc[teamGB[1]] = gb1;
    const [ry0, ry1] = Math.random() < 0.5 ? axisRY : [axisRY[1], axisRY[0]];
    cc[teamRY[0]] = ry0;
    cc[teamRY[1]] = ry1;

    return cc as ColorCorner;
}

export function assignCornersFFA(playerCount: '1v1' | '4P' = '4P'): ColorCorner {
    const cc: Partial<ColorCorner> = {};
    const allColors: PlayerColor[] = ['green', 'red', 'yellow', 'blue'];
    const corners: Corner[] = ['BL', 'BR', 'TR', 'TL'];

    if (playerCount === '1v1') {
        // For 1v1, we MUST ensure the two active players (first two in LOBBY_COLORS)
        // are diagonally opposite. We'll pick one axis randomly.
        // The remaining colors still receive the unused diagonal so coordinate
        // lookups remain total even though they are not seated in this match.
        const axis = Math.random() < 0.5 ? ['BL', 'TR'] : ['BR', 'TL'];
        const otherAxis = axis[0] === 'BL' ? ['BR', 'TL'] : ['BL', 'TR'];
        
        // Randomly assign the first two colors to the chosen axis
        const [c0, c1] = Math.random() < 0.5 ? axis : [axis[1], axis[0]];
        cc[allColors[0]] = c0 as Corner; // Host (Green)
        cc[allColors[2]] = c1 as Corner; // Guest (Yellow)
        
        // Assign remaining colors to the other axis
        const [c2, c3] = Math.random() < 0.5 ? otherAxis : [otherAxis[1], otherAxis[0]];
        cc[allColors[1]] = c2 as Corner; // Red
        cc[allColors[3]] = c3 as Corner; // Blue
    } else {
        // Fisher-Yates shuffle corners for 4P
        for (let i = corners.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [corners[i], corners[j]] = [corners[j], corners[i]];
        }
        // Assign all 4 colors to corners
        allColors.forEach((color, i) => { cc[color] = corners[i]; });
    }

    return cc as ColorCorner;
}
