'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface DiceProps {
    onRoll: (value: number) => void;
    currentValue?: number | null;
    isRolling?: boolean;
    disabled?: boolean;
}

const DOT_POSITIONS = {
    1: [[50, 50]],
    2: [[25, 25], [75, 75]],
    3: [[20, 20], [50, 50], [80, 80]],
    4: [[25, 25], [25, 75], [75, 25], [75, 75]],
    5: [[20, 20], [20, 80], [50, 50], [80, 20], [80, 80]],
    6: [[25, 20], [25, 50], [25, 80], [75, 20], [75, 50], [75, 80]]
};

export default function Dice({ onRoll, currentValue, isRolling: externalIsRolling, disabled }: DiceProps) {
    const isRolling = externalIsRolling;

    // Sync with external value when not rolling
    useEffect(() => {
        if (!isRolling && currentValue !== undefined && currentValue !== null) {
            setDisplayedValue(currentValue);
        }
    }, [currentValue, isRolling]);

    // Handle face cycling during roll
    useEffect(() => {
        let interval: NodeJS.Timeout;
        if (isRolling) {
            interval = setInterval(() => {
                setDisplayedValue(Math.floor(Math.random() * 6) + 1);
            }, 80); // Fast cycling for motion feel
        }
        return () => clearInterval(interval);
    }, [isRolling]);

    const roll = () => {
        if (isRolling || disabled) return;
        // Trigger engine roll - value will be generated by useGameActions
        onRoll(0); 
    };

    const renderDots = (num: number) => {
        const positions = DOT_POSITIONS[num as keyof typeof DOT_POSITIONS] || [];
        return positions.map(([cx, cy], i) => (
            <g key={i}>
                {/* Dot Inner Shadow / Hole effect */}
                <circle cx={cx} cy={cy + 0.5} r="9.5" fill="rgba(0,0,0,0.1)" />
                <circle cx={cx} cy={cy} r="8.5" fill="#0F172A" className="dice-dot-svg" />
            </g>
        ));
    };

    return (
        <div className="dice-container">
            <button
                className={`dice-btn ${isRolling ? 'rolling' : ''}`}
                onClick={roll}
                disabled={disabled || isRolling}
                title={disabled ? (isRolling ? "Rolling..." : "Wait for your turn") : "Roll Dice"}
                style={{ width: 48, height: 48 }}
            >
                <motion.svg
                    viewBox="0 0 100 100"
                    className="dice-svg"
                    animate={isRolling ? { 
                        rotate: [0, 90, 180, 270, 360],
                        y: [0, -10, 0, -5, 0],
                        scale: [1, 1.1, 0.95, 1.05, 1],
                    } : { rotate: 0, y: 0, scale: 1 }}
                    transition={isRolling ? { 
                        rotate: { repeat: Infinity, duration: 0.6, ease: "linear" },
                        y: { repeat: Infinity, duration: 0.4, ease: "easeInOut" },
                        scale: { repeat: Infinity, duration: 0.4 }
                    } : { duration: 0.3, type: "spring", stiffness: 300 }}
                >
                    <defs>
                        <linearGradient id="diceBodyGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                            <stop offset="0%" stopColor="#FFFFFF" />
                            <stop offset="30%" stopColor="#F8F8F5" />
                            <stop offset="100%" stopColor="#E5E2D8" />
                        </linearGradient>
                        
                        <linearGradient id="diceBevelGrad" x1="0%" y1="0%" x2="0%" y2="100%">
                            <stop offset="0%" stopColor="rgba(0,0,0,0.12)" />
                            <stop offset="100%" stopColor="rgba(255,255,255,1)" />
                        </linearGradient>

                        <filter id="diceInnerShadow">
                            <feOffset dx="0" dy="2" />
                            <feGaussianBlur stdDeviation="2" result="offset-blur" />
                            <feComposite operator="out" in="SourceGraphic" in2="offset-blur" result="inverse" />
                            <feFlood floodColor="black" floodOpacity="0.4" result="color" />
                            <feComposite operator="in" in="color" in2="inverse" result="shadow" />
                            <feComposite operator="over" in="shadow" in2="SourceGraphic" />
                        </filter>

                        <filter id="diceOuterShadow" x="-20%" y="-20%" width="140%" height="140%">
                            <feDropShadow dx="0" dy="6" stdDeviation="5" floodColor="rgba(0,0,0,0.18)" />
                            <feDropShadow dx="0" dy="2" stdDeviation="2" floodColor="rgba(0,0,0,0.12)" />
                        </filter>
                    </defs>

                    {/* Main Body with stronger shadow */}
                    <rect
                        x="3" y="3" width="94" height="94" rx="26" ry="26"
                        fill="url(#diceBodyGrad)"
                        filter="url(#diceOuterShadow)"
                    />

                    {/* Recessed Face - Much more pronounced bevel */}
                    <rect
                        x="10" y="10" width="80" height="80" rx="20" ry="20"
                        fill="rgba(0,0,0,0.04)"
                        filter="url(#diceInnerShadow)"
                    />

                    {/* Bright Highlights on the edges to simulate material catch-light */}
                    <rect
                        x="11" y="11" width="78" height="78" rx="19" ry="19"
                        fill="none"
                        stroke="rgba(255,255,255,0.9)"
                        strokeWidth="1.5"
                    />

                    {/* Subtle surface shine over the whole thing */}
                    <rect
                        x="3" y="3" width="94" height="94" rx="26" ry="26"
                        fill="none"
                        stroke="url(#diceBevelGrad)"
                        strokeWidth="1.2"
                        opacity="0.6"
                    />

                    {/* Dots / Face */}
                    <AnimatePresence mode="wait">
                        <motion.g
                            key={`face-${isRolling ? 'rolling-' + displayedValue : displayedValue}`}
                            initial={isRolling ? { opacity: 0.4 } : { opacity: 0, scale: 0.5 }}
                            animate={{ opacity: 1, scale: 1 }}
                            exit={isRolling ? { opacity: 0.4 } : { opacity: 0, scale: 0.5 }}
                            transition={{ duration: isRolling ? 0.05 : 0.2 }}
                        >
                            {renderDots(displayedValue)}
                        </motion.g>
                    </AnimatePresence>
                </motion.svg>
            </button>

            <style jsx>{`
                .dice-container {
                    display: flex;
                    align-items: center;
                    justify-content: center;
                }

                .dice-btn {
                    padding: 0;
                    margin: 0;
                    background: transparent;
                    border: none;
                    cursor: pointer;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    outline: none;
                    transition: transform 0.2s cubic-bezier(0.175, 0.885, 0.32, 1.275);
                    border-radius: 12px;
                }

                .dice-svg {
                    width: 48px;
                    height: 48px;
                    filter: drop-shadow(0 4px 10px rgba(0,0,0,0.2));
                }

                .dice-dot-svg {
                    filter: drop-shadow(0 1px 0px rgba(0,0,0,0.15));
                }

                .dice-btn:hover:not(:disabled) {
                    transform: translateY(-3px) scale(1.08);
                }

                .dice-btn:hover:not(:disabled) .dice-svg {
                    filter: drop-shadow(0 6px 12px rgba(0,0,0,0.18)) drop-shadow(0 2px 4px rgba(0,0,0,0.1));
                }

                .dice-btn:active:not(:disabled) {
                    transform: translateY(1px) scale(0.96);
                }

                .dice-btn:disabled {
                    cursor: not-allowed;
                    opacity: 0.6;
                }

                .rolling {
                    /* CSS animation removed in favor of smoother Framer Motion tumble */
                }
            `}</style>
        </div>
    );
}
